name = "NahaGraphs"
uuid = "fd225a7d-cc45-47cf-8742-8ffafb057088"
authors = ["MarkNahabedian <naha@mit.edu> and contributors"]
version = "0.1.0"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
